concept("TryCatch",|cwd:///src/org/rascalmpl/library/experiments/RascalTutor/Courses/Rascal/Statements/TryCatch/TryCatch.concept|,[],[],{"Language"},{"Exception","Throw"},""," \<pre class=\"listing\"\>try\n   \<i\>Statement\</i\>\<sub\>1\</sub\>;\ncatch \<i\>PatternWithAction\</i\>\<sub\>1\</sub\>;\ncatch \<i\>PatternWithAction\</i\>\<sub\>2\</sub\>;\n...\ncatch: \<i\>Statement\</i\>\<sub\>2\</sub\>;\nfinally: \<i\>Statement\</i\>\<sub\>3\</sub\>;\n\</pre\>","","",{"try",";","catch",":","finally"}," A try catch statement has as purpose to catch any \<a href=\"/show?concept=Exception\"\>Exception\</a\>s that are raised during the execution of \<code\>\<i\>Statement\</i\>\<sub\>1\</sub\>\</code\>.\n These exceptions may caused by:\n  \<ul\>\<li\> The execution of an explicit \<a href=\"/show?concept=Throw\"\>Throw\</a\> statement.\</li\>\n\<li\> The Rascal system that discovers an abnormal condition, e.g., an out of bounds error when accessing a list element.\</li\>\n\</ul\> Note that all elements of the try catch statement are optional but that at least one has to be present. \n Their meaning is as follows:\n  \<ul\>\<li\> If a pattern of some \<code\>\<i\>PatternWithAction\</i\>\<sub\>i\</sub\>\</code\> matches, the corresponding action is executed.\</li\>\n\<li\> Otherwise, \<code\>\<i\>Statement\</i\>\<sub\>2\</sub\>\</code\> is executed (when present).\</li\>\n\<li\> Before leaving the try catch statement \<code\>\<i\>Statement\</i\>\<sub\>3\</sub\>\</code\> is always executed (when present).\</li\>\n\</ul\>","","","",[])